@set allusersprofile=c:\programdata
@set appdata=c:\users\inter\appdata\roaming
@set clion=c:\program files\jetbrains\clion 2020.1.2\bin
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=jules_imf
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set homedrive=c:
@set homepath=\users\inter
@set include=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\atlmfc\include;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\include;c:\program files (x86)\windows kits\10\include\10.0.18362.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.18362.0\shared;c:\program files (x86)\windows kits\10\include\10.0.18362.0\um;c:\program files (x86)\windows kits\10\include\10.0.18362.0\winrt;c:\program files (x86)\windows kits\10\include\10.0.18362.0\cppwinrt
@set lib=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\lib\x64;c:\program files (x86)\windows kits\10\lib\10.0.18362.0\ucrt\x64;c:\program files (x86)\windows kits\10\lib\10.0.18362.0\um\x64
@set libpath=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.18362.0;c:\program files (x86)\windows kits\10\references\10.0.18362.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\inter\appdata\local
@set logonserver=\\jules_imf
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set number_of_processors=8
@set onedrive=c:\users\inter\onedrive
@set onedriveconsumer=c:\users\inter\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\\extensions\microsoft\intellicode\cli;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\bin\hostx64\x64;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2019\community\msbuild\current\bin\roslyn;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools\x64;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\\x64;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x64;c:\program files (x86)\windows kits\10\bin\x64;c:\program files (x86)\microsoft visual studio\2019\community\\msbuild\current\bin;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x64;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x86;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\mingw\bin;c:\program files\010 editor;c;c:\users\inter\source\repos\jules cpu\x64\debug;c:\users\inter\appdata\local\microsoft\windowsapps;c:\program files\jetbrains\pycharm community edition 2020.1.2\bin;c:\program files\jetbrains\clion 2020.1.2\bin;c:\users\inter\appdata\local\programs\microsoft vs code\bin;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\ninja
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\inter\appdata\local\microsoft\visualstudio\16.0_7309d25b\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 142 stepping 12, genuineintel
@set processor_level=6
@set processor_revision=8e0c
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtools_extensionspath_vs2017=c:\windows\microsoft.net\framework64\
@set pvsbuildtools_extensionspath_vs2019=c:\program files (x86)\microsoft visual studio\2019\community\msbuild
@set pvsbuildtools_installdir_vs2019=c:\program files (x86)\microsoft visual studio\2019\community
@set pycharm community edition=c:\program files\jetbrains\pycharm community edition 2020.1.2\bin
@set servicehublogsessionkey=ea96da97
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\inter\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\inter\appdata\local\temp
@set ucrtversion=10.0.18362.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=jules_imf
@set userdomain_roamingprofile=jules_imf
@set username=julesimf
@set userprofile=c:\users\inter
@set vbox_msi_install_path=c:\program files\oracle\virtualbox\
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2019\community\vc\redist\msvc\14.27.29016\
@set vctoolsversion=14.27.29110
@set visualstudiodir=c:\users\inter\onedrive\¤®ªã¬¥­âë\visual studio 2019
@set visualstudioedition=microsoft visual studio communityÿ2019
@set visualstudioversion=16.0
@set vs160comntools=c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=16.7.5
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\
@set vslang=1049
@set vsskuedition=community
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.18362.0;c:\program files (x86)\windows kits\10\references\10.0.18362.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.18362.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.18362.0\
@set windowssdkversion=10.0.18362.0\
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.27.29110\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x64;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x86;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\mingw\bin;c:\program files\010 editor;c;c:\users\inter\source\repos\jules cpu\x64\debug;c:\users\inter\appdata\local\microsoft\windowsapps;c:\program files\jetbrains\pycharm community edition 2020.1.2\bin;c:\program files\jetbrains\clion 2020.1.2\bin;c:\users\inter\appdata\local\programs\microsoft vs code\bin
@set __vscmd_script_err_count=0

@call "cl.exe" @"C:\Users\inter\source\repos\Jules CPU\Jules Assembler\Main.c.PVS-Studio.preprocess.cmd.rsp" 2>&1